### ISSUE TITLE
SymbolTable is not thread-safe

### ISSUE THREAD

**Issue by brendankowitz** [FirelyTeam/firely-net-sdk#1884]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

:information_source: Is your bug report about Firely Server Facade, please send an email to [server@fire.ly](mailto:server@fire.ly) or submit a bug report to Jira if you are a paying customer.

**Describe the bug**
I occasionally see these errors in our logs:

```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Hl7.FhirPath.Expressions.SymbolTable.Filter(String name, Int32 argCount)
   at Hl7.FhirPath.Expressions.EvaluatorVisitor.resolve(SymbolTable scope, String name, IEnumerable`1 argumentTypes)
   at Hl7.FhirPath.Expressions.EvaluatorVisitor.VisitFunctionCall(FunctionCallExpression expression, SymbolTable scope)
   at Hl7.FhirPath.Expressions.FunctionCallExpression.Accept[T](ExpressionVisitor`1 visitor, SymbolTable scope)
   at Hl7.FhirPath.Expressions.EvaluatorExpressionExtensions.ToEvaluator(Expression expr, SymbolTable scope)
   at Hl7.FhirPath.FhirPathCompiler.Compile(Expression expression)
   at Hl7.FhirPath.FhirPathCompiler.Compile(String expression)
   at Hl7.FhirPath.IValueProviderFPExtensions.Compile(String expression)
   at Hl7.FhirPath.IValueProviderFPExtensions.<>c.<.cctor>b__9_0(String expr)
   at Hl7.Fhir.Utility.Cache`2.<>c__DisplayClass13_0.<.ctor>b__0(K key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hl7.Fhir.Utility.Cache`2.GetValue(K key)
```

Given that SymbolTable is held statically:

https://github.com/FirelyTeam/firely-net-common/blob/develop/src/Hl7.FhirPath/FhirPath/FhirPathCompiler.cs#L25

A guess is that it is possible Add is called while another process is Filtering:

https://github.com/FirelyTeam/firely-net-common/blob/75ff0d288c1e3945ed0ef0b0f81868918785e3d1/src/Hl7.FhirPath/FhirPath/Expressions/SymbolTable.cs#L91-L105

**To Reproduce**
1. TBD, we should be able to design a unit test for this

**Expected behavior**
Multiple threads can compile expressions at the same time

**Screenshots**
N/A

**Version used:**
 - FHIR Version: [e.g. STU3, R4, R5]
 - Version: [e.g. 1.9.0]

**Additional context**

**Comment by marcovisserFurore** [comment]
Hi @brendankowitz,

Thanks for letting us know. I tried to create a unit test for this:

```c#
        public void Issue_1884()
        {

            Task[] taskArray = new Task[10];
            for (int i = 0; i < taskArray.Length; i++)
            {
                taskArray[i] = new Task(compile);
            }

            try
            {
                Parallel.ForEach<Task>(taskArray, (t) => { t.Start(); });
                Task.WaitAll(taskArray);

            }
            catch (Exception ex)
            {
                Assert.Fail(ex.Message + " " + ex.StackTrace);
            }

            void compile()
            {
                var compiler = new FhirPathCompiler();
                compiler.Symbols.Add<ITypedElement, bool, string, EvaluationContext, ITypedElement>("check", Check);
                compiler.Compile("(CapabilityStatement.useContext.value as Quantity) | (CapabilityStatement.useContext.value as Range)");

                static ITypedElement Check(ITypedElement elem, bool condition, string message, EvaluationContext ctx) => elem;
            }
        }
```

And I get the `InvalidOperationException` (_Collection was modified; enumeration operation may not execute_). But when I do not add symbols to the compiler and just use the default symbols (lazy initialized) then I don't get this  `InvalidOperationException` .

Can it be that you are adding extra symbols to the symboltable? Most likely you use the method `AddFhirExtensions`.

When you first create the `SymbolTable` yourself and then create the FhirPathCompiler, then you won't have these problems:

```c#
                var symbolTable = new SymbolTable();
                symbolTable.AddStandardFP();
                symbolTable.AddFhirExtensions();

                var compiler = new FhirPathCompiler(symbolTable);
```

I know, it is workaround. In the meantime I will find a solution.

**Comment by brendankowitz** [comment]
Thanks for looking into this Marco, this is mostly likely whats happening
