### ISSUE TITLE
uri param value Length limit on  SearchUsingPostAsync

### ISSUE THREAD

**Issue by yochail** [FirelyTeam/firely-net-sdk#2299]
When using BaseFhirClient "SearchUsingPostAsync" Methode,  if one of the SearchParams value is longer then 65520 chars,
an exception will be thrown

**To Reproduce**
```
var client = new BaseFhirClient()
client.SearchUsingPostAsync(new SearchParams("code","<long string (see attached file)>", "Patient")
```
[long string example](https://github.com/FirelyTeam/firely-net-sdk/files/10012019/long.string.bug.txt)
an exception will be thrown:
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at System.Net.Http.FormUrlEncodedContent.Encode(String data)
   at System.Net.Http.FormUrlEncodedContent.GetContentByteArray(IEnumerable`1 nameValueCollection)
   at System.Net.Http.FormUrlEncodedContent..ctor(IEnumerable`1 nameValueCollection)
   at Hl7.Fhir.Rest.BundleToEntryRequest.<setBodyAndContentTypeAsync>d__3.MoveNext()
   at Hl7.Fhir.Rest.BundleToEntryRequest.<ToEntryRequestAsync>d__1.MoveNext()
   at Hl7.Fhir.Rest.BaseFhirClient.<executeAsync>d__94`1.MoveNext()

**Expected behavior**
The post request parameters length should be unrestricted, or restricted and documented properly

**Version used:**
 - FHIR Version: R4
 - Version: 4.0.0

**Additional context**
The restriction is comming from using .ner "EscapeDataString" with has a limit of c_MaxUriBufferSize=0xFFF0=65520
[see limit in .net source code](
https://github.com/microsoft/referencesource/blob/dae14279dd0672adead5de00ac8f117dcf74c184/System/net/System/UriHelper.cs#L125)

**Comment by marcovisserFurore** [comment]
Hi @yochail,

Thanks for issue. This restriction is coming from the .NET library. See also the Microsoft issue [14674](https://github.com/dotnet/runtime/issues/14674). The size restriction has been solved from `net5.0`. I presume you are using an older version (.NET Framework 4.x perhaps?). Upgrading the framework of your application will solve this issue.

There is a workaround (see https://github.com/dotnet/runtime/issues/14674#issuecomment-114565197) which can be applied to our SDK.  We are thinking about to integrate this, although we plan to remove target framework net452.

**Comment by mmsmits** [comment]
We dropped support for net452 some time ago.
